configuration for "pic16f1827" is
end configuration;

testbench for "pic16f1827" is
begin

      process is
         begin
            wait for 2000ms;
            
            RCREG <= 16#FE#;   // Address of uninitialized stations
            PIR1.RCIF <= '1';

            wait for 570us;
            if PIR1.RCIF == '1' then
                RCSTA.OERR <= '1';
            end if;
            RCREG <= 03;    // Read register
            PIR1.RCIF <= '1';
            wait for 570us;
            if PIR1.RCIF == '1' then
                RCSTA.OERR <= '1';
            end if;
            RCREG <= 0;     // Addres H
            PIR1.RCIF <= '1';
            wait for 570us;
            if PIR1.RCIF == '1' then
                RCSTA.OERR <= '1';
            end if;
            RCREG <= 0;     // Address L
            PIR1.RCIF <= '1';
            wait for 570us;
            if PIR1.RCIF == '1' then
                RCSTA.OERR <= '1';
            end if;
            RCREG <= 0;     // Size H
            PIR1.RCIF <= '1';
            wait for 570us;
            if PIR1.RCIF == '1' then
                RCSTA.OERR <= '1';
            end if;
            RCREG <= 8;     // Size L
            PIR1.RCIF <= '1';

            wait for 570us;

            if PIR1.RCIF == '1' then
                RCSTA.OERR <= '1';
            end if;
            RCREG <= 16#51#;     // Crc Lo
            PIR1.RCIF <= '1';
            wait for 570us;
            if PIR1.RCIF == '1' then
                RCSTA.OERR <= '1';
            end if;
            RCREG <= 16#51#;     // Crc Hi
            PIR1.RCIF <= '1';

            wait for 570us;

            // etc..
         end process;
end testbench;
